### PR TITLE
fix(work): increase max timeout from 1 day to 3 days

### PR DESCRIPTION
**Pull request by tjzegmott**
Small change to the max timeout for the Work object.

Signed-off-by: Tarik Zegmott <tarik.zegmott@mcgill.ca>

### CODE REVIEW

**Review by chrisfandrade16 — APPROVED** [review]
Seems like a good simple change.

**Comment by tjzegmott** [comment]
Do you foresee any issues with allowing work to run for that long before timing out? I know that the default is still an hour.

**Comment by chrisfandrade16** [comment]
So basically this means if a Work gets stuck, the default timeout is now 3 hours right. Perhaps it could be an issue for anytime using Work objects who aren't aware of the work.timeout property and rely on the 1 hour timeout for their scheduling. But at least at CHAMPSS we've always set custom work.timeout values, in the past some greater than 60 minutes but now less than 60 minutes. I haven't seen any issues. Not sure if @odarotto has any other wisdom here.

**Comment by chrisfandrade16** [comment]
Oh sorry, this is _max_ timeout, I misunderstood, my bad. Hmmm...hard to see how that could affect things. This would essentially just allow people to make greater timeouts...there could be other spots in workflow that checks for a 60 minute timeout, we'll have to check. I wouldn't know any off the top of my head.

**Comment by tjzegmott** [comment]
Okay, we will wait for @odarotto's comments before merging this.

**Review by odarotto — APPROVED** [review]
LGTM

**Pull request merged**
