### PR TITLE
94 feat improve cli commands

### PR DESCRIPTION
**Pull request by odarotto**

### CODE REVIEW

**Comment by chrisfandrade16** [comment]
Just curious, did you decide on any way to show the deployments with the worflow CLI, or shall we make a separate issue for that?

**Comment by chrisfandrade16** [comment]
Another question: is it possible to get a pipeline simply by its name only? Or, can there be mulitple pipelines with the same name? It might be easier for users to remember the name, then the ids. And so, if the names are unique, allowing either the name or id to be used (but not needing both, as this PR addressed), could be useful.

**Review by tjzegmott — APPROVED** [review]
LGTM

**Comment by odarotto** [comment]
> Just curious, did you decide on any way to show the deployments with the worflow CLI, or shall we make a separate issue for that?

Yes I will create separate issue for this.

**Comment by odarotto** [comment]
> Another question: is it possible to get a single pipeline simply by its name only? Or, can there be mulitple pipelines with the same name? It might be easier for users to remember the name, than the ids. And so, if the names are unique, allowing either the name or id to be used in the CLI (but not needing both, as this PR addressed), could be useful.

Since a `Config` can generate several pipelines, all of these pipelines live under the same name, also a user can send 2 `Config` with the same name but that generate different pipeline. I think for `Config` we should leave the requirement for <name> <id> and for `Pipeline` use only the <id>.

**Pull request merged**
